imports_granularity = "Crate"
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
group_imports = "StdExternalCrate"
max_width = 80
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
edition = "2021"
unstable_features = true
